Some updates + small fixes
mikepenz/AboutLibraries pull request #526
Opened 2020-09-01 15:28 UTC by cyb3rko

I removed non working links from the README, updated some dependencies, fixed some spelling mistakes :) and removed a redundant identifier.

2020-09-01 15:35 UTC, mikepenz requested changes

2020-09-01 15:35 UTC, mikepenz commented on build.gradle
> +                appcompat       : '1.3.0-alpha02',
I think we should stay with stable releases

2020-09-01 15:36 UTC, mikepenz commented
Thank you so much for the PR really appreciate. Please see the change request I mentioned

2020-09-17 20:21 UTC, cyb3rko commented
Did I miss something that I have to do to allow this PR to get merged or do you just wait for the next release?

2020-09-18 06:45 UTC, mikepenz commented
@cyb3rko sorry, thins have been very busy. Yes please see the change here to stay with the stable release for the dependency: https://github.com/mikepenz/AboutLibraries/pull/526/files#diff-c197962302397baf3a4cc36463dce5eaR18

2020-09-18 11:58 UTC, merged