Spelling
mikepenz/AboutLibraries pull request #659
Opened 2021-06-13 19:27 UTC by jsoref

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/AboutLibraries/commit/f342234acc32123165fcca9f9172070c0609796c#commitcomment-52104826

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/AboutLibraries/commit/966fb2e5193115916ffb16af204779f01277bc46

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

2021-06-13 19:28 UTC, jsoref commented on README.md
> +Exports all libraries in a CSV format with the name, artifactId, and licenseId. And a separate list with all licenses used, and a potential list of unmatched libraries / licenses.
This should be fine

2021-06-13 19:28 UTC, jsoref commented on aboutlibraries-definitions/src/main/res/values/library_cardsuiforandroid_strings.xml
> +    <string name="library_cardsuiForAndroid_libraryDescription">Google’s Now popular Cards UI has everyone fascinated. This library aims to mimic this widget.
This library seems to be dead. Otherwise, I'd send a PR to fix its spelling. I'm happy to drop this (or any other change).

2021-06-13 19:28 UTC, jsoref commented on aboutlibraries-definitions/src/main/res/values/library_paymill_strings.xml
> +    <string name="library_paymill_licenseContent"></string>
I'm not sure what's going on w/ this

2021-06-13 19:28 UTC, jsoref commented on aboutlibraries-definitions/src/main/res/values/library_sugarorm_strings.xml
> +    <string name="library_sugarorm_licenseContent">
I'm not sure what's going on w/ this

2021-06-13 19:28 UTC, jsoref commented on app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.kt
> +                        // create and launch an activity in minimal design without any additional modifications
This should be fine

2021-06-13 19:28 UTC, jsoref commented on configurations.gradle
> +ext.getPropertyOrDefault = { key, defau ->
This is scary

2021-06-28 13:22 UTC, hamedtayeban commented on README.md
> +Exports all libraries in a CSV format with the name, artifactId, and licenseId. And a separate list with all licenses used, and a potential list of unmatched libraries / licenses.
[]()

2021-06-28 13:22 UTC, hamedtayeban requested changes
<147bf706-d9c8-4784-babb-c4a6c70a4dfc>

2021-07-02 07:06 UTC, mikepenz approved these changes
Thank you very much

2021-07-02 07:06 UTC, merged