Jetbrains Qodana
mikepenz/AboutLibraries pull request #842
Opened 2023-02-07 14:57 UTC by mikepenz

- add Qodana to AboutLibs CI build

2023-02-19 08:20 UTC, kristian579 commented
100ezr Help bitw

2023-09-09 07:25 UTC, tfalc69 commented
Git

2024-05-07 07:51 UTC, zuzanabi requested changes
[temp1009349010518859318.pdf](https://github.com/mikepenz/AboutLibraries/files/15232078/temp1009349010518859318.pdf)

2024-05-07 07:51 UTC, zuzanabi commented
[](url)

> * add Qodana to AboutLibs CI build

2024-05-07 07:51 UTC, zuzanabi commented
[Xodo Document - samsung.z.bittner@gmail.pdf.pdf](https://github.com/mikepenz/AboutLibraries/files/15232086/Xodo.Document.-.samsung.z.bittner%40gmail.pdf.pdf)


> * add Qodana to AboutLibs CI build



# A first-level heading
## A second-level heading
### A third-level heading

2025-05-06 18:44 UTC, closed without merging